knight: &base
  width: 600
  height: 825
  explode: "qty"
  data: tilt.csv
  template: knight.js
  _color: RED
  pdf:
    trim_lines: true
    bleed: 37.5
    margin: 0.25
  format:
    - png
    - pdf

blue_knight:
  <<: *base
  _color: BLUE
